<?php
// comment ...

// 公開領域のルートパス（HTTP）
// define("HTTP_ROOT", "http://" . SERVER_NAME);
// 公開領域のルートパス（内部）
// define("DOCUMENT_ROOT", "/htdocs/training");
// 本サーバのルートパス
// define("REAL_ROOT", "");
// comment ...
// comment ...
// comment ...
$ary = array(
	array(
		'name' => '', 
		'width' => 178, 
		'height' => '', 
		'exp' => '.jpg'
	), 
	array(
		'name' => '_1', 
		'width' => 110, 
		'height' => '', 
		'exp' => '.jpg'
	)
);
setDefineArray('IMAGE_TEST', $ary);
// comment ...
// comment ...

$ary = array(
	array(
		'name' => '', 
		'width' => 178, 
		'height' => '', 
		'exp' => '.jpg'
	), 
	array(
		'name' => '_1', 
		'width' => 110, 
		'height' => '', 
		'exp' => '.jpg'
	)
);
setDefineArray('IMAGE_TEST_2222', $ary);